### ISSUE TITLE
DDA-алгоритм

### ISSUE THREAD

**Issue by become-iron** [group-1652-2014/tasks#4]
Выяснилось, что DDA-алгоритм делали одновременно два человека: я и Лина Воробьёва. Хоть темы работ и одинаковые, подходы совершенно разные
* [Работа Лина](https://github.com/LinaVorob/DDA--lines)
* [Моя](https://github.com/become-iron/diff-python-scripts/tree/master/dda)

**Comment by futoke** [comment]
Ок, ваши работы я уже оценил, работу Лины буду оценивать отдельно. Вот, чтобы такого не было, я с самого начала предлагал вписываться в лист, чтобы знать кто и что пишет, и либо объединяться в группы, либо выбирать другие темы.
